# Generated by Django 3.0.4 on 2020-03-13 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='morador',
            options={'verbose_name_plural': 'moradores'},
        ),
        migrations.CreateModel(
            name='Habitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_do_apartamento', models.IntegerField()),
                ('identificacao_do_projecto', models.CharField(max_length=200)),
                ('localizacao', models.CharField(max_length=200)),
                ('iniciativa', models.CharField(choices=[('PU', 'pública'), ('PP', 'pública-privada'), ('PR', 'privada'), ('OU', 'outros')], default='PU', max_length=2)),
                ('tipologia', models.CharField(choices=[('T1', 'tipologia T1'), ('T2', 'tipologia T2'), ('T3', 'tipologia T3'), ('T4', 'tipologia T4')], default='T2', max_length=2)),
                ('andar', models.ImageField(upload_to='')),
                ('numero_de_compartimentos', models.ImageField(upload_to='')),
                ('estado_legal', models.CharField(choices=[('CP', 'Compra'), ('RE', 'Renda')], max_length=2)),
                ('alienado_ao_inh', models.BooleanField(default=True)),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Morador')),
            ],
        ),
    ]
