# Generated by Django 3.0.4 on 2020-03-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20200313_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitacao',
            options={'verbose_name_plural': 'habitações'},
        ),
        migrations.AlterField(
            model_name='habitacao',
            name='numero_do_apartamento',
            field=models.CharField(max_length=100),
        ),
    ]
